id: P004194
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:59:59.788532
source_metadata:
  id: bdr:W1KG22376
  title: ནཱ་རོ་མཁའ་སྤྱོད་མའི་བསྐྱེད་རིམ་གྱི་ཁྲིད་རྡོ་རྗེ་མཁའ་འགྲོ་མ་རྣམས་ཀྱི་སྙིང་གི་ཐིག་ལེ།
  author: ''
  volumes:
    03445f315fe34d1cb43cb33f6a700cff:
      image_group_id: I1KG22394
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
