id: opecha:P004194
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22376
  title: ནཱ་རོ་མཁའ་སྤྱོད་མའི་བསྐྱེད་རིམ་གྱི་ཁྲིད་རྡོ་རྗེ་མཁའ་འགྲོ་མ་རྣམས་ཀྱི་སྙིང་གི་ཐིག་ལེ།
  volume: ''
  author: ''
