id: I3210CA54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:19:03+00:00'
last_modified: '2022-06-07T20:58:06.389998+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22376
  title: ནཱ་རོ་མཁའ་སྤྱོད་མའི་བསྐྱེད་རིམ་གྱི་ཁྲིད་རྡོ་རྗེ་མཁའ་འགྲོ་མ་རྣམས་ཀྱི་སྙིང་གི་ཐིག་ལེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0900:
      image_group_id: I1KG22394
      title: ''
      total_pages: 134
      order: 1
      base_file: 0900.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
